create table if not exists public.device_tokens (
  token text primary key,
  user_id text not null,
  device_id text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists device_tokens_user_id_idx
  on public.device_tokens (user_id);

create table if not exists public.recording_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  kind text not null,
  created_at timestamptz not null default now()
);

create index if not exists recording_usage_user_created_idx
  on public.recording_usage (user_id, created_at desc);
