create table if not exists public.device_tokens (
  token text primary key,
  user_id text not null,
  device_id text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists device_tokens_user_id_idx
  on public.device_tokens (user_id);

create table if not exists public.recording_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  kind text not null,
  created_at timestamptz not null default now()
);

create index if not exists recording_usage_user_created_idx
  on public.recording_usage (user_id, created_at desc);

create table if not exists public.contact_sales_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null check (source in ('contact_sales', 'download_gate')),
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'spam')),
  name text,
  email text not null,
  company text,
  use_case text,
  ip_hash text,
  user_agent text
);

create index if not exists contact_sales_leads_created_idx
  on public.contact_sales_leads (created_at desc);

create index if not exists contact_sales_leads_email_created_idx
  on public.contact_sales_leads (email, created_at desc);

create index if not exists contact_sales_leads_ip_hash_created_idx
  on public.contact_sales_leads (ip_hash, created_at desc);
